Handling the backend DBMS selection better. Removed JIRA and Confluence version numbers from DB names and paths. Updated paths to support more recent defaults from Atlassian.

diff --git a/bin/atlassian-backup b/bin/atlassian-backup
--- a/bin/atlassian-backup
+++ b/bin/atlassian-backup
@@ -39,6 +39,12 @@ function setup() {
         eval MYSQL_USER="\$${TOOL_NAME}_MYSQL_USER"
         eval MYSQL_PASS="\$${TOOL_NAME}_MYSQL_PASS"
         eval MYSQL_HOST="\$${TOOL_NAME}_MYSQL_HOST"
+        echo "MySQL has been selected as the backen DBMS"
+    elif [ "${DB_BACKEND}" = 'pg' ]; then
+        echo "PostgreSQL has been selected as the backen DBMS"
+    else
+        echo "ERROR: No such DB_BACKEND '$DB_BACKEND'" 1>&2
+        exit 2
     fi
     eval DB_NAME="\$${TOOL_NAME}_DB_NAME"
 
@@ -69,8 +75,11 @@ function dump_database() {
     DATABASE_DUMP_OUTPUT="${OUTPUT_PREFIX}-database-dump.sql.gz"
     if [ "${DB_BACKEND}" = 'mysql' ]; then
         $MYENGINE --single-transaction --host="$MYSQL_HOST" --user="$MYSQL_USER" --password="$MYSQL_PASS" "$DB_NAME" | gzip > "$DATABASE_DUMP_OUTPUT"
-    else
+    elif [ "${DB_BACKEND}" = 'pg' ]; then
         $PGENGINE/pg_dump "$DB_NAME" | gzip > "$DATABASE_DUMP_OUTPUT"
+    else
+        echo "ERROR: No such DB_BACKEND '$DB_BACKEND'" 1>&2
+        exit 2
     fi
     echo "    Created $DATABASE_DUMP_OUTPUT"
 }
