Added mysql support (#1)
Added mysql support

diff --git a/bin/atlassian-backup b/bin/atlassian-backup
--- a/bin/atlassian-backup
+++ b/bin/atlassian-backup
@@ -34,6 +34,18 @@ function setup() {
     eval BACKUP_DIR="\$${TOOL_NAME}_BACKUP_DIR"
     eval ATTACHMENTS_PATH="\$${TOOL_NAME}_ATTACHMENTS_PATH"
     eval CONFIGURATION_PATH="\$${TOOL_NAME}_CONFIGURATION_PATH"
+    eval DB_BACKEND="\$${TOOL_NAME}_DB_BACKEND"
+    if [ "${DB_BACKEND}" = 'mysql' ]; then
+        eval MYSQL_USER="\$${TOOL_NAME}_MYSQL_USER"
+        eval MYSQL_PASS="\$${TOOL_NAME}_MYSQL_PASS"
+        eval MYSQL_HOST="\$${TOOL_NAME}_MYSQL_HOST"
+        echo "MySQL has been selected as the backen DBMS"
+    elif [ "${DB_BACKEND}" = 'pg' ]; then
+        echo "PostgreSQL has been selected as the backen DBMS"
+    else
+        echo "ERROR: No such DB_BACKEND '$DB_BACKEND'" 1>&2
+        exit 2
+    fi
     eval DB_NAME="\$${TOOL_NAME}_DB_NAME"
 
     LC_TOOL_NAME=$(echo "$NATURAL_TOOL_NAME" | tr '[A-Z]' '[a-z]')
@@ -61,7 +73,14 @@ function backup_attachments() {
 function dump_database() {
     echo "  - Dumping $NATURAL_TOOL_NAME database"
     DATABASE_DUMP_OUTPUT="${OUTPUT_PREFIX}-database-dump.sql.gz"
-    $PGENGINE/pg_dump "$DB_NAME" | gzip > "$DATABASE_DUMP_OUTPUT"
+    if [ "${DB_BACKEND}" = 'mysql' ]; then
+        $MYENGINE --single-transaction --host="$MYSQL_HOST" --user="$MYSQL_USER" --password="$MYSQL_PASS" "$DB_NAME" | gzip > "$DATABASE_DUMP_OUTPUT"
+    elif [ "${DB_BACKEND}" = 'pg' ]; then
+        $PGENGINE/pg_dump "$DB_NAME" | gzip > "$DATABASE_DUMP_OUTPUT"
+    else
+        echo "ERROR: No such DB_BACKEND '$DB_BACKEND'" 1>&2
+        exit 2
+    fi
     echo "    Created $DATABASE_DUMP_OUTPUT"
 }
 
